# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.24
# 

Name:       perl-XML-Parser

# >> macros
# << macros

Summary:    A low level Perl module for parsing XML either via trees or streaming
Version:    2.41
Release:    1
Group:      Development/Libraries
License:    GPL+ or Artistic
URL:        http://search.cpan.org/dist/XML-Parser/
Source0:    http://www.cpan.org/authors/id/T/TO/TODDR/XML-Parser-%{version}.tar.gz
Source100:  perl-XML-Parser.yaml
Requires:   perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))
Requires:   perl(LWP), perl(URI)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  expat-devel
BuildRequires:  perl(LWP), perl(URI)

%description
This module provides ways to parse XML documents. It is built on top
of XML::Parser::Expat, which is a lower level interface to James
Clark's expat library. Each call to one of the parsing methods creates
a new instance of XML::Parser::Expat which is then used to parse the
document. Expat options may be provided when the XML::Parser object is
created. These options are then passed on to the Expat object on each
parse call. They can also be given as extra arguments to the parse
methods, in which case they override options given at XML::Parser
creation time.



%prep
%setup -q -n XML-Parser-%{version}

# >> setup
chmod 644 samples/{canonical,xml*}
%{__perl} -pi -e 's|^#!/usr/local/bin/perl\b|#!%{__perl}|' samples/{canonical,xml*}
# << setup

%build
# >> build pre
CFLAGS="$RPM_OPT_FLAGS" %{__perl} Makefile.PL INSTALLDIRS=vendor
# << build pre


make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} ';'
find $RPM_BUILD_ROOT -type f -name perllocal.pod -exec rm -f {} ';'
find $RPM_BUILD_ROOT -type f -name '*.bs' -a -size 0 -exec rm -f {} ';'
find $RPM_BUILD_ROOT -type d -depth -exec rmdir {} 2>/dev/null ';'
chmod -R u+w $RPM_BUILD_ROOT/*

for file in samples/REC-xml-19980210.xml; do
iconv -f iso-8859-1 -t utf-8 < "$file" > "${file}_"
mv -f "${file}_" "$file"
done
# << install post


%check
# >> check
make test
# << check

%files
%defattr(-,root,root,-)
# >> files
%doc README Changes samples/
%{perl_vendorarch}/XML/
%{perl_vendorarch}/auto/XML/
%doc %{_mandir}/man3/*.3*
# << files
